// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cbData.BE.DB.DataContext;

#nullable disable

namespace cbData.BE.DB.Migrations
{
    [DbContext(typeof(CbDataDbContext))]
    [Migration("20250201192633_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateUtcDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 47,
                            Quantity = 103,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4007)
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 92,
                            Quantity = 48,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4038)
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 96,
                            Quantity = 4,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4055)
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 70,
                            Quantity = 95,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4074)
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 69,
                            Quantity = 14,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4091)
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 67,
                            Quantity = 45,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4111)
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 19,
                            Quantity = 182,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4128)
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 94,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4147)
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 96,
                            Quantity = 134,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4162)
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 70,
                            Quantity = 64,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4182)
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 46,
                            Quantity = 163,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4197)
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 10,
                            Quantity = 41,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4262)
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 57,
                            Quantity = 159,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4279)
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 1,
                            Quantity = 7,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4298)
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 11,
                            Quantity = 195,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4313)
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 75,
                            Quantity = 198,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4333)
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 59,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4349)
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 82,
                            Quantity = 128,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4370)
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 8,
                            Quantity = 19,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4386)
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 47,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4403)
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 88,
                            Quantity = 64,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4419)
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 40,
                            Quantity = 140,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4437)
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 17,
                            Quantity = 45,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4454)
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 58,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4471)
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 93,
                            Quantity = 102,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4487)
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 73,
                            Quantity = 197,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4504)
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 79,
                            Quantity = 59,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4520)
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 99,
                            Quantity = 19,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4538)
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 77,
                            Quantity = 32,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4554)
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 21,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4573)
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 10,
                            Quantity = 62,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4620)
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 17,
                            Quantity = 58,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4639)
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 38,
                            Quantity = 141,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4655)
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 50,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4676)
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 48,
                            Quantity = 135,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4691)
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 80,
                            Quantity = 121,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4710)
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 15,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4725)
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 19,
                            Quantity = 162,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4743)
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 77,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4758)
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 40,
                            Quantity = 71,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4776)
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 63,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4792)
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 89,
                            Quantity = 13,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4810)
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 94,
                            Quantity = 186,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4825)
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 36,
                            Quantity = 164,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4843)
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 67,
                            Quantity = 168,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4858)
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 47,
                            Quantity = 147,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4875)
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 31,
                            Quantity = 84,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4892)
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 3,
                            Quantity = 100,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4909)
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 97,
                            Quantity = 36,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(4995)
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 16,
                            Quantity = 77,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5014)
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 81,
                            Quantity = 81,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5030)
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 86,
                            Quantity = 140,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5048)
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 28,
                            Quantity = 5,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5063)
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 55,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5081)
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 24,
                            Quantity = 198,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5096)
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 83,
                            Quantity = 164,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5114)
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 37,
                            Quantity = 159,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5129)
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 72,
                            Quantity = 24,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5147)
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 85,
                            Quantity = 154,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5163)
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 58,
                            Quantity = 144,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5181)
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 96,
                            Quantity = 90,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5197)
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 30,
                            Quantity = 142,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5214)
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 85,
                            Quantity = 33,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5230)
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 18,
                            Quantity = 180,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5248)
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 38,
                            Quantity = 56,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5264)
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 18,
                            Quantity = 106,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5386)
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 19,
                            Quantity = 86,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5403)
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 36,
                            Quantity = 89,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5422)
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 21,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5439)
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 31,
                            Quantity = 126,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5457)
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 75,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5473)
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 10,
                            Quantity = 171,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5491)
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 24,
                            Quantity = 153,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5507)
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 61,
                            Quantity = 11,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5525)
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 37,
                            Quantity = 133,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5541)
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 7,
                            Quantity = 11,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5559)
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 15,
                            Quantity = 123,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5574)
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 17,
                            Quantity = 74,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5592)
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 49,
                            Quantity = 137,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5608)
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 23,
                            Quantity = 14,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5626)
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 88,
                            Quantity = 66,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5641)
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 32,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5659)
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 50,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5675)
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 27,
                            Quantity = 104,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5693)
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 16,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5764)
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 52,
                            Quantity = 18,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5786)
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 7,
                            Quantity = 36,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5803)
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 50,
                            Quantity = 153,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5821)
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 93,
                            Quantity = 1,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5837)
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 74,
                            Quantity = 191,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5854)
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 46,
                            Quantity = 190,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5870)
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 6,
                            Quantity = 57,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5887)
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 38,
                            Quantity = 113,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5903)
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 1,
                            Quantity = 82,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5921)
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 66,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5937)
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 81,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5956)
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 25,
                            Quantity = 140,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5972)
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 79,
                            Quantity = 91,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 97,
                            Quantity = 111,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6006)
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 27,
                            Quantity = 49,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6024)
                        },
                        new
                        {
                            Id = 101,
                            ProductId = 45,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6040)
                        },
                        new
                        {
                            Id = 102,
                            ProductId = 93,
                            Quantity = 103,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6058)
                        },
                        new
                        {
                            Id = 103,
                            ProductId = 69,
                            Quantity = 59,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6075)
                        },
                        new
                        {
                            Id = 104,
                            ProductId = 97,
                            Quantity = 89,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6093)
                        },
                        new
                        {
                            Id = 105,
                            ProductId = 44,
                            Quantity = 108,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6153)
                        },
                        new
                        {
                            Id = 106,
                            ProductId = 85,
                            Quantity = 34,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6173)
                        },
                        new
                        {
                            Id = 107,
                            ProductId = 73,
                            Quantity = 150,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6189)
                        },
                        new
                        {
                            Id = 108,
                            ProductId = 23,
                            Quantity = 100,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6207)
                        },
                        new
                        {
                            Id = 109,
                            ProductId = 92,
                            Quantity = 148,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6223)
                        },
                        new
                        {
                            Id = 110,
                            ProductId = 1,
                            Quantity = 38,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6242)
                        },
                        new
                        {
                            Id = 111,
                            ProductId = 11,
                            Quantity = 129,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6258)
                        },
                        new
                        {
                            Id = 112,
                            ProductId = 50,
                            Quantity = 80,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6276)
                        },
                        new
                        {
                            Id = 113,
                            ProductId = 99,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6292)
                        },
                        new
                        {
                            Id = 114,
                            ProductId = 85,
                            Quantity = 183,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6310)
                        },
                        new
                        {
                            Id = 115,
                            ProductId = 49,
                            Quantity = 60,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6326)
                        },
                        new
                        {
                            Id = 116,
                            ProductId = 29,
                            Quantity = 28,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6344)
                        },
                        new
                        {
                            Id = 117,
                            ProductId = 59,
                            Quantity = 21,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6359)
                        },
                        new
                        {
                            Id = 118,
                            ProductId = 21,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6378)
                        },
                        new
                        {
                            Id = 119,
                            ProductId = 30,
                            Quantity = 126,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6393)
                        },
                        new
                        {
                            Id = 120,
                            ProductId = 57,
                            Quantity = 86,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6411)
                        },
                        new
                        {
                            Id = 121,
                            ProductId = 24,
                            Quantity = 192,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6426)
                        },
                        new
                        {
                            Id = 122,
                            ProductId = 93,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6444)
                        },
                        new
                        {
                            Id = 123,
                            ProductId = 93,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6460)
                        },
                        new
                        {
                            Id = 124,
                            ProductId = 43,
                            Quantity = 168,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6478)
                        },
                        new
                        {
                            Id = 125,
                            ProductId = 91,
                            Quantity = 186,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6566)
                        },
                        new
                        {
                            Id = 126,
                            ProductId = 84,
                            Quantity = 178,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6586)
                        },
                        new
                        {
                            Id = 127,
                            ProductId = 27,
                            Quantity = 20,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6602)
                        },
                        new
                        {
                            Id = 128,
                            ProductId = 74,
                            Quantity = 76,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6621)
                        },
                        new
                        {
                            Id = 129,
                            ProductId = 43,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6636)
                        },
                        new
                        {
                            Id = 130,
                            ProductId = 7,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6657)
                        },
                        new
                        {
                            Id = 131,
                            ProductId = 58,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6674)
                        },
                        new
                        {
                            Id = 132,
                            ProductId = 75,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6692)
                        },
                        new
                        {
                            Id = 133,
                            ProductId = 98,
                            Quantity = 86,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6709)
                        },
                        new
                        {
                            Id = 134,
                            ProductId = 93,
                            Quantity = 117,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6726)
                        },
                        new
                        {
                            Id = 135,
                            ProductId = 49,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6742)
                        },
                        new
                        {
                            Id = 136,
                            ProductId = 84,
                            Quantity = 41,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6760)
                        },
                        new
                        {
                            Id = 137,
                            ProductId = 32,
                            Quantity = 94,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6776)
                        },
                        new
                        {
                            Id = 138,
                            ProductId = 23,
                            Quantity = 7,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6794)
                        },
                        new
                        {
                            Id = 139,
                            ProductId = 11,
                            Quantity = 172,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6809)
                        },
                        new
                        {
                            Id = 140,
                            ProductId = 57,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6900)
                        },
                        new
                        {
                            Id = 141,
                            ProductId = 31,
                            Quantity = 47,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6916)
                        },
                        new
                        {
                            Id = 142,
                            ProductId = 16,
                            Quantity = 153,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6935)
                        },
                        new
                        {
                            Id = 143,
                            ProductId = 63,
                            Quantity = 65,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6951)
                        },
                        new
                        {
                            Id = 144,
                            ProductId = 99,
                            Quantity = 151,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6970)
                        },
                        new
                        {
                            Id = 145,
                            ProductId = 70,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(6985)
                        },
                        new
                        {
                            Id = 146,
                            ProductId = 46,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7004)
                        },
                        new
                        {
                            Id = 147,
                            ProductId = 10,
                            Quantity = 177,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7020)
                        },
                        new
                        {
                            Id = 148,
                            ProductId = 65,
                            Quantity = 178,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7038)
                        },
                        new
                        {
                            Id = 149,
                            ProductId = 84,
                            Quantity = 152,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7053)
                        },
                        new
                        {
                            Id = 150,
                            ProductId = 96,
                            Quantity = 19,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7071)
                        },
                        new
                        {
                            Id = 151,
                            ProductId = 16,
                            Quantity = 150,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7088)
                        },
                        new
                        {
                            Id = 152,
                            ProductId = 58,
                            Quantity = 109,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7105)
                        },
                        new
                        {
                            Id = 153,
                            ProductId = 11,
                            Quantity = 125,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7222)
                        },
                        new
                        {
                            Id = 154,
                            ProductId = 15,
                            Quantity = 138,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7249)
                        },
                        new
                        {
                            Id = 155,
                            ProductId = 24,
                            Quantity = 12,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7266)
                        },
                        new
                        {
                            Id = 156,
                            ProductId = 19,
                            Quantity = 13,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7285)
                        },
                        new
                        {
                            Id = 157,
                            ProductId = 38,
                            Quantity = 120,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7301)
                        },
                        new
                        {
                            Id = 158,
                            ProductId = 90,
                            Quantity = 9,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7319)
                        },
                        new
                        {
                            Id = 159,
                            ProductId = 91,
                            Quantity = 12,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7397)
                        },
                        new
                        {
                            Id = 160,
                            ProductId = 51,
                            Quantity = 13,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7419)
                        },
                        new
                        {
                            Id = 161,
                            ProductId = 87,
                            Quantity = 69,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7435)
                        },
                        new
                        {
                            Id = 162,
                            ProductId = 46,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7455)
                        },
                        new
                        {
                            Id = 163,
                            ProductId = 89,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7472)
                        },
                        new
                        {
                            Id = 164,
                            ProductId = 77,
                            Quantity = 56,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7491)
                        },
                        new
                        {
                            Id = 165,
                            ProductId = 72,
                            Quantity = 9,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7507)
                        },
                        new
                        {
                            Id = 166,
                            ProductId = 7,
                            Quantity = 116,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7524)
                        },
                        new
                        {
                            Id = 167,
                            ProductId = 68,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7540)
                        },
                        new
                        {
                            Id = 168,
                            ProductId = 4,
                            Quantity = 184,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7558)
                        },
                        new
                        {
                            Id = 169,
                            ProductId = 27,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7573)
                        },
                        new
                        {
                            Id = 170,
                            ProductId = 69,
                            Quantity = 86,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7591)
                        },
                        new
                        {
                            Id = 171,
                            ProductId = 3,
                            Quantity = 177,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7606)
                        },
                        new
                        {
                            Id = 172,
                            ProductId = 62,
                            Quantity = 140,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7624)
                        },
                        new
                        {
                            Id = 173,
                            ProductId = 20,
                            Quantity = 12,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7640)
                        },
                        new
                        {
                            Id = 174,
                            ProductId = 60,
                            Quantity = 74,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7658)
                        },
                        new
                        {
                            Id = 175,
                            ProductId = 62,
                            Quantity = 93,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7673)
                        },
                        new
                        {
                            Id = 176,
                            ProductId = 3,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7692)
                        },
                        new
                        {
                            Id = 177,
                            ProductId = 59,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7708)
                        },
                        new
                        {
                            Id = 178,
                            ProductId = 90,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7726)
                        },
                        new
                        {
                            Id = 179,
                            ProductId = 12,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7771)
                        },
                        new
                        {
                            Id = 180,
                            ProductId = 28,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7790)
                        },
                        new
                        {
                            Id = 181,
                            ProductId = 27,
                            Quantity = 21,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7806)
                        },
                        new
                        {
                            Id = 182,
                            ProductId = 81,
                            Quantity = 199,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7824)
                        },
                        new
                        {
                            Id = 183,
                            ProductId = 29,
                            Quantity = 199,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7840)
                        },
                        new
                        {
                            Id = 184,
                            ProductId = 34,
                            Quantity = 14,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7858)
                        },
                        new
                        {
                            Id = 185,
                            ProductId = 85,
                            Quantity = 32,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7874)
                        },
                        new
                        {
                            Id = 186,
                            ProductId = 55,
                            Quantity = 106,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7892)
                        },
                        new
                        {
                            Id = 187,
                            ProductId = 87,
                            Quantity = 39,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7908)
                        },
                        new
                        {
                            Id = 188,
                            ProductId = 68,
                            Quantity = 199,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7927)
                        },
                        new
                        {
                            Id = 189,
                            ProductId = 74,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7942)
                        },
                        new
                        {
                            Id = 190,
                            ProductId = 22,
                            Quantity = 196,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7961)
                        },
                        new
                        {
                            Id = 191,
                            ProductId = 42,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7977)
                        },
                        new
                        {
                            Id = 192,
                            ProductId = 68,
                            Quantity = 102,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(7995)
                        },
                        new
                        {
                            Id = 193,
                            ProductId = 30,
                            Quantity = 181,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8010)
                        },
                        new
                        {
                            Id = 194,
                            ProductId = 70,
                            Quantity = 42,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8028)
                        },
                        new
                        {
                            Id = 195,
                            ProductId = 81,
                            Quantity = 100,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8044)
                        },
                        new
                        {
                            Id = 196,
                            ProductId = 39,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8063)
                        },
                        new
                        {
                            Id = 197,
                            ProductId = 79,
                            Quantity = 75,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8080)
                        },
                        new
                        {
                            Id = 198,
                            ProductId = 88,
                            Quantity = 28,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8157)
                        },
                        new
                        {
                            Id = 199,
                            ProductId = 1,
                            Quantity = 74,
                            UpdateUtcDateTime = new DateTime(2025, 2, 1, 19, 26, 32, 730, DateTimeKind.Utc).AddTicks(8175)
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Product 99"
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.HasOne("cbData.BE.DB.Models.Products.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
