// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cbData.BE.DB.DataContext;

#nullable disable

namespace cbData.BE.DB.Migrations
{
    [DbContext(typeof(CbDataDbContext))]
    [Migration("20250130153637_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateUtcDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 73,
                            Quantity = 44,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7262)
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 68,
                            Quantity = 38,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7324)
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 98,
                            Quantity = 174,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7361)
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 63,
                            Quantity = 143,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7402)
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 46,
                            Quantity = 71,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7438)
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 90,
                            Quantity = 42,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7481)
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            Quantity = 50,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7517)
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 66,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7557)
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 42,
                            Quantity = 176,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7678)
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 19,
                            Quantity = 145,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7724)
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 48,
                            Quantity = 143,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7760)
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 33,
                            Quantity = 9,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7800)
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 23,
                            Quantity = 114,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7834)
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 94,
                            Quantity = 113,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7875)
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 24,
                            Quantity = 28,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 55,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7949)
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 67,
                            Quantity = 117,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(7986)
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 33,
                            Quantity = 8,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8029)
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Quantity = 133,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8063)
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 32,
                            Quantity = 28,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8105)
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 23,
                            Quantity = 183,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8140)
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 6,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8181)
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 16,
                            Quantity = 8,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8217)
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 34,
                            Quantity = 83,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8258)
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 76,
                            Quantity = 1,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8293)
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 17,
                            Quantity = 136,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8332)
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 95,
                            Quantity = 185,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8365)
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 25,
                            Quantity = 75,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8487)
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 50,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8524)
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 20,
                            Quantity = 25,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8565)
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 42,
                            Quantity = 95,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8600)
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 34,
                            Quantity = 124,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8642)
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 22,
                            Quantity = 154,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8678)
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 16,
                            Quantity = 65,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8723)
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 74,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8760)
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 49,
                            Quantity = 93,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8799)
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 49,
                            Quantity = 39,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8835)
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 98,
                            Quantity = 108,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8875)
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 94,
                            Quantity = 50,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8911)
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 32,
                            Quantity = 144,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8948)
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 83,
                            Quantity = 55,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(8982)
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 13,
                            Quantity = 172,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9021)
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 60,
                            Quantity = 83,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9056)
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 56,
                            Quantity = 83,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9096)
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 91,
                            Quantity = 108,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9131)
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 91,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9250)
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 96,
                            Quantity = 32,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9289)
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 32,
                            Quantity = 188,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9326)
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 85,
                            Quantity = 9,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9360)
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 21,
                            Quantity = 120,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9400)
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 73,
                            Quantity = 50,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9435)
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 84,
                            Quantity = 143,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9473)
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 28,
                            Quantity = 158,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9507)
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 90,
                            Quantity = 71,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9546)
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 30,
                            Quantity = 110,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9581)
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 50,
                            Quantity = 97,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9621)
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 96,
                            Quantity = 36,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9658)
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 39,
                            Quantity = 158,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9698)
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 86,
                            Quantity = 187,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9733)
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 55,
                            Quantity = 149,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9771)
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 19,
                            Quantity = 32,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9807)
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 77,
                            Quantity = 127,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9847)
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 8,
                            Quantity = 34,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9882)
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 85,
                            Quantity = 18,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9921)
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 95,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 215, DateTimeKind.Utc).AddTicks(9956)
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 73,
                            Quantity = 97,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(63)
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 74,
                            Quantity = 118,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(101)
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 19,
                            Quantity = 172,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(142)
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 89,
                            Quantity = 121,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(177)
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 25,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(218)
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 61,
                            Quantity = 16,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(253)
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 61,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(293)
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 94,
                            Quantity = 48,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(330)
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 42,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(371)
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 8,
                            Quantity = 59,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(406)
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 27,
                            Quantity = 131,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(446)
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 54,
                            Quantity = 93,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(481)
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 83,
                            Quantity = 109,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(522)
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 60,
                            Quantity = 156,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(556)
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 73,
                            Quantity = 158,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(595)
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 85,
                            Quantity = 173,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(632)
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 14,
                            Quantity = 187,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(848)
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 8,
                            Quantity = 74,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(900)
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 85,
                            Quantity = 56,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(941)
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 95,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(978)
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 73,
                            Quantity = 37,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1018)
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 25,
                            Quantity = 185,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1054)
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 62,
                            Quantity = 186,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1095)
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 53,
                            Quantity = 14,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 11,
                            Quantity = 145,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1173)
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 23,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1209)
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 46,
                            Quantity = 99,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1248)
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 15,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1283)
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 96,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1324)
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 21,
                            Quantity = 137,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1360)
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 65,
                            Quantity = 198,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1402)
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 72,
                            Quantity = 35,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1437)
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 30,
                            Quantity = 12,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1476)
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 76,
                            Quantity = 137,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1513)
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 24,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1551)
                        },
                        new
                        {
                            Id = 101,
                            ProductId = 62,
                            Quantity = 1,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1589)
                        },
                        new
                        {
                            Id = 102,
                            ProductId = 94,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1793)
                        },
                        new
                        {
                            Id = 103,
                            ProductId = 9,
                            Quantity = 59,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1834)
                        },
                        new
                        {
                            Id = 104,
                            ProductId = 97,
                            Quantity = 106,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1874)
                        },
                        new
                        {
                            Id = 105,
                            ProductId = 89,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1911)
                        },
                        new
                        {
                            Id = 106,
                            ProductId = 33,
                            Quantity = 21,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1950)
                        },
                        new
                        {
                            Id = 107,
                            ProductId = 28,
                            Quantity = 87,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(1986)
                        },
                        new
                        {
                            Id = 108,
                            ProductId = 17,
                            Quantity = 73,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2026)
                        },
                        new
                        {
                            Id = 109,
                            ProductId = 39,
                            Quantity = 192,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2060)
                        },
                        new
                        {
                            Id = 110,
                            ProductId = 89,
                            Quantity = 149,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2100)
                        },
                        new
                        {
                            Id = 111,
                            ProductId = 64,
                            Quantity = 184,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2137)
                        },
                        new
                        {
                            Id = 112,
                            ProductId = 3,
                            Quantity = 2,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2175)
                        },
                        new
                        {
                            Id = 113,
                            ProductId = 64,
                            Quantity = 70,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2214)
                        },
                        new
                        {
                            Id = 114,
                            ProductId = 39,
                            Quantity = 67,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2254)
                        },
                        new
                        {
                            Id = 115,
                            ProductId = 42,
                            Quantity = 17,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2290)
                        },
                        new
                        {
                            Id = 116,
                            ProductId = 63,
                            Quantity = 145,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2329)
                        },
                        new
                        {
                            Id = 117,
                            ProductId = 18,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2366)
                        },
                        new
                        {
                            Id = 118,
                            ProductId = 9,
                            Quantity = 27,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2406)
                        },
                        new
                        {
                            Id = 119,
                            ProductId = 24,
                            Quantity = 100,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2441)
                        },
                        new
                        {
                            Id = 120,
                            ProductId = 24,
                            Quantity = 98,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2482)
                        },
                        new
                        {
                            Id = 121,
                            ProductId = 46,
                            Quantity = 72,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2516)
                        },
                        new
                        {
                            Id = 122,
                            ProductId = 94,
                            Quantity = 54,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2641)
                        },
                        new
                        {
                            Id = 123,
                            ProductId = 51,
                            Quantity = 132,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2682)
                        },
                        new
                        {
                            Id = 124,
                            ProductId = 75,
                            Quantity = 186,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2724)
                        },
                        new
                        {
                            Id = 125,
                            ProductId = 14,
                            Quantity = 43,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2760)
                        },
                        new
                        {
                            Id = 126,
                            ProductId = 61,
                            Quantity = 14,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2800)
                        },
                        new
                        {
                            Id = 127,
                            ProductId = 40,
                            Quantity = 23,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2833)
                        },
                        new
                        {
                            Id = 128,
                            ProductId = 86,
                            Quantity = 180,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2872)
                        },
                        new
                        {
                            Id = 129,
                            ProductId = 52,
                            Quantity = 153,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2911)
                        },
                        new
                        {
                            Id = 130,
                            ProductId = 96,
                            Quantity = 91,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2959)
                        },
                        new
                        {
                            Id = 131,
                            ProductId = 2,
                            Quantity = 2,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(2994)
                        },
                        new
                        {
                            Id = 132,
                            ProductId = 9,
                            Quantity = 30,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3035)
                        },
                        new
                        {
                            Id = 133,
                            ProductId = 80,
                            Quantity = 197,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3070)
                        },
                        new
                        {
                            Id = 134,
                            ProductId = 77,
                            Quantity = 31,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3111)
                        },
                        new
                        {
                            Id = 135,
                            ProductId = 98,
                            Quantity = 199,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3147)
                        },
                        new
                        {
                            Id = 136,
                            ProductId = 97,
                            Quantity = 51,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3188)
                        },
                        new
                        {
                            Id = 137,
                            ProductId = 8,
                            Quantity = 128,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3356)
                        },
                        new
                        {
                            Id = 138,
                            ProductId = 19,
                            Quantity = 91,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3400)
                        },
                        new
                        {
                            Id = 139,
                            ProductId = 90,
                            Quantity = 51,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3437)
                        },
                        new
                        {
                            Id = 140,
                            ProductId = 65,
                            Quantity = 63,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3480)
                        },
                        new
                        {
                            Id = 141,
                            ProductId = 94,
                            Quantity = 43,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3515)
                        },
                        new
                        {
                            Id = 142,
                            ProductId = 43,
                            Quantity = 101,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3556)
                        },
                        new
                        {
                            Id = 143,
                            ProductId = 72,
                            Quantity = 16,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3591)
                        },
                        new
                        {
                            Id = 144,
                            ProductId = 5,
                            Quantity = 126,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3629)
                        },
                        new
                        {
                            Id = 145,
                            ProductId = 36,
                            Quantity = 170,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3663)
                        },
                        new
                        {
                            Id = 146,
                            ProductId = 51,
                            Quantity = 160,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3703)
                        },
                        new
                        {
                            Id = 147,
                            ProductId = 48,
                            Quantity = 101,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3739)
                        },
                        new
                        {
                            Id = 148,
                            ProductId = 98,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3780)
                        },
                        new
                        {
                            Id = 149,
                            ProductId = 99,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3817)
                        },
                        new
                        {
                            Id = 150,
                            ProductId = 75,
                            Quantity = 98,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3856)
                        },
                        new
                        {
                            Id = 151,
                            ProductId = 67,
                            Quantity = 136,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3891)
                        },
                        new
                        {
                            Id = 152,
                            ProductId = 8,
                            Quantity = 29,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3929)
                        },
                        new
                        {
                            Id = 153,
                            ProductId = 17,
                            Quantity = 128,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(3965)
                        },
                        new
                        {
                            Id = 154,
                            ProductId = 54,
                            Quantity = 192,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4005)
                        },
                        new
                        {
                            Id = 155,
                            ProductId = 20,
                            Quantity = 187,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4041)
                        },
                        new
                        {
                            Id = 156,
                            ProductId = 52,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4217)
                        },
                        new
                        {
                            Id = 157,
                            ProductId = 53,
                            Quantity = 73,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4260)
                        },
                        new
                        {
                            Id = 158,
                            ProductId = 22,
                            Quantity = 161,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4299)
                        },
                        new
                        {
                            Id = 159,
                            ProductId = 65,
                            Quantity = 177,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4335)
                        },
                        new
                        {
                            Id = 160,
                            ProductId = 47,
                            Quantity = 195,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4377)
                        },
                        new
                        {
                            Id = 161,
                            ProductId = 25,
                            Quantity = 152,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4411)
                        },
                        new
                        {
                            Id = 162,
                            ProductId = 94,
                            Quantity = 70,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4451)
                        },
                        new
                        {
                            Id = 163,
                            ProductId = 29,
                            Quantity = 143,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4487)
                        },
                        new
                        {
                            Id = 164,
                            ProductId = 84,
                            Quantity = 191,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4526)
                        },
                        new
                        {
                            Id = 165,
                            ProductId = 48,
                            Quantity = 28,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4561)
                        },
                        new
                        {
                            Id = 166,
                            ProductId = 43,
                            Quantity = 66,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4601)
                        },
                        new
                        {
                            Id = 167,
                            ProductId = 81,
                            Quantity = 25,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4636)
                        },
                        new
                        {
                            Id = 168,
                            ProductId = 52,
                            Quantity = 84,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4678)
                        },
                        new
                        {
                            Id = 169,
                            ProductId = 37,
                            Quantity = 70,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4713)
                        },
                        new
                        {
                            Id = 170,
                            ProductId = 31,
                            Quantity = 57,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4757)
                        },
                        new
                        {
                            Id = 171,
                            ProductId = 29,
                            Quantity = 161,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4792)
                        },
                        new
                        {
                            Id = 172,
                            ProductId = 62,
                            Quantity = 121,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4831)
                        },
                        new
                        {
                            Id = 173,
                            ProductId = 61,
                            Quantity = 137,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4869)
                        },
                        new
                        {
                            Id = 174,
                            ProductId = 84,
                            Quantity = 81,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(4908)
                        },
                        new
                        {
                            Id = 175,
                            ProductId = 81,
                            Quantity = 144,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5136)
                        },
                        new
                        {
                            Id = 176,
                            ProductId = 64,
                            Quantity = 104,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5276)
                        },
                        new
                        {
                            Id = 177,
                            ProductId = 26,
                            Quantity = 86,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5314)
                        },
                        new
                        {
                            Id = 178,
                            ProductId = 70,
                            Quantity = 17,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5355)
                        },
                        new
                        {
                            Id = 179,
                            ProductId = 84,
                            Quantity = 79,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5392)
                        },
                        new
                        {
                            Id = 180,
                            ProductId = 64,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5431)
                        },
                        new
                        {
                            Id = 181,
                            ProductId = 43,
                            Quantity = 41,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5468)
                        },
                        new
                        {
                            Id = 182,
                            ProductId = 2,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5506)
                        },
                        new
                        {
                            Id = 183,
                            ProductId = 13,
                            Quantity = 22,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5540)
                        },
                        new
                        {
                            Id = 184,
                            ProductId = 61,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5580)
                        },
                        new
                        {
                            Id = 185,
                            ProductId = 3,
                            Quantity = 103,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5614)
                        },
                        new
                        {
                            Id = 186,
                            ProductId = 35,
                            Quantity = 66,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5654)
                        },
                        new
                        {
                            Id = 187,
                            ProductId = 54,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5689)
                        },
                        new
                        {
                            Id = 188,
                            ProductId = 67,
                            Quantity = 10,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5728)
                        },
                        new
                        {
                            Id = 189,
                            ProductId = 69,
                            Quantity = 130,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5763)
                        },
                        new
                        {
                            Id = 190,
                            ProductId = 76,
                            Quantity = 126,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5805)
                        },
                        new
                        {
                            Id = 191,
                            ProductId = 49,
                            Quantity = 44,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5840)
                        },
                        new
                        {
                            Id = 192,
                            ProductId = 99,
                            Quantity = 76,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5879)
                        },
                        new
                        {
                            Id = 193,
                            ProductId = 29,
                            Quantity = 130,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5912)
                        },
                        new
                        {
                            Id = 194,
                            ProductId = 13,
                            Quantity = 37,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5953)
                        },
                        new
                        {
                            Id = 195,
                            ProductId = 90,
                            Quantity = 65,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(5988)
                        },
                        new
                        {
                            Id = 196,
                            ProductId = 9,
                            Quantity = 146,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(6196)
                        },
                        new
                        {
                            Id = 197,
                            ProductId = 87,
                            Quantity = 0,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(6234)
                        },
                        new
                        {
                            Id = 198,
                            ProductId = 73,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(6273)
                        },
                        new
                        {
                            Id = 199,
                            ProductId = 60,
                            Quantity = 32,
                            UpdateUtcDateTime = new DateTime(2025, 1, 30, 15, 36, 36, 216, DateTimeKind.Utc).AddTicks(6310)
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Name = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Name = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Name = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            Name = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            Name = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            Name = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            Name = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            Name = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            Name = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            Name = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            Name = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            Description = "",
                            Name = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            Description = "",
                            Name = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            Description = "",
                            Name = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            Description = "",
                            Name = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            Description = "",
                            Name = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            Description = "",
                            Name = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            Description = "",
                            Name = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            Description = "",
                            Name = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            Description = "",
                            Name = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            Description = "",
                            Name = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            Description = "",
                            Name = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            Description = "",
                            Name = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            Description = "",
                            Name = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            Description = "",
                            Name = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            Description = "",
                            Name = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            Description = "",
                            Name = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            Description = "",
                            Name = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            Description = "",
                            Name = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            Description = "",
                            Name = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            Description = "",
                            Name = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            Description = "",
                            Name = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            Description = "",
                            Name = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            Description = "",
                            Name = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            Description = "",
                            Name = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            Description = "",
                            Name = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            Description = "",
                            Name = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            Description = "",
                            Name = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            Description = "",
                            Name = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            Description = "",
                            Name = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            Description = "",
                            Name = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            Description = "",
                            Name = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            Description = "",
                            Name = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            Description = "",
                            Name = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            Description = "",
                            Name = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            Description = "",
                            Name = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            Description = "",
                            Name = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            Description = "",
                            Name = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            Description = "",
                            Name = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            Description = "",
                            Name = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            Description = "",
                            Name = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            Description = "",
                            Name = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            Description = "",
                            Name = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            Description = "",
                            Name = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            Description = "",
                            Name = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            Description = "",
                            Name = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            Description = "",
                            Name = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            Description = "",
                            Name = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            Description = "",
                            Name = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            Description = "",
                            Name = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            Description = "",
                            Name = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            Description = "",
                            Name = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            Description = "",
                            Name = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            Description = "",
                            Name = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            Description = "",
                            Name = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            Description = "",
                            Name = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            Description = "",
                            Name = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            Description = "",
                            Name = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            Description = "",
                            Name = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            Description = "",
                            Name = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            Description = "",
                            Name = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            Description = "",
                            Name = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            Description = "",
                            Name = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            Description = "",
                            Name = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            Description = "",
                            Name = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            Description = "",
                            Name = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            Description = "",
                            Name = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            Description = "",
                            Name = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            Description = "",
                            Name = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            Description = "",
                            Name = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            Description = "",
                            Name = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            Description = "",
                            Name = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            Description = "",
                            Name = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            Description = "",
                            Name = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            Description = "",
                            Name = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            Description = "",
                            Name = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            Description = "",
                            Name = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            Description = "",
                            Name = "Product 99"
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.HasOne("cbData.BE.DB.Models.Products.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
