// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cbData.BE.DB.DataContext;

#nullable disable

namespace cbData.BE.DB.Migrations
{
    [DbContext(typeof(CbDataDbContext))]
    [Migration("20250203182021_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateUtcDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "PK");

                    b.ToTable("Orders", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 70,
                            Quantity = 198,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2532)
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 91,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2567)
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 78,
                            Quantity = 197,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2581)
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 87,
                            Quantity = 99,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2598)
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 88,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2611)
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 86,
                            Quantity = 58,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2628)
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 79,
                            Quantity = 180,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2641)
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 97,
                            Quantity = 49,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2657)
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 85,
                            Quantity = 109,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 94,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2686)
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 39,
                            Quantity = 148,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2699)
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 63,
                            Quantity = 43,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2714)
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 28,
                            Quantity = 165,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2728)
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 26,
                            Quantity = 141,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2743)
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 75,
                            Quantity = 128,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2756)
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 85,
                            Quantity = 177,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2771)
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 38,
                            Quantity = 113,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2819)
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 17,
                            Quantity = 91,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2840)
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 26,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2853)
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 15,
                            Quantity = 192,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2869)
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 46,
                            Quantity = 147,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2883)
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 58,
                            Quantity = 177,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2898)
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 68,
                            Quantity = 149,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2912)
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 19,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2928)
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 15,
                            Quantity = 191,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2941)
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 96,
                            Quantity = 123,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2957)
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 80,
                            Quantity = 57,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2971)
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 78,
                            Quantity = 130,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(2986)
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 83,
                            Quantity = 116,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3000)
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 3,
                            Quantity = 129,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3015)
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 83,
                            Quantity = 179,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3028)
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 47,
                            Quantity = 22,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3043)
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 33,
                            Quantity = 154,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3057)
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 60,
                            Quantity = 112,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3074)
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 74,
                            Quantity = 168,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3122)
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 38,
                            Quantity = 120,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3138)
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 77,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3152)
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 78,
                            Quantity = 78,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3168)
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 43,
                            Quantity = 152,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3181)
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 42,
                            Quantity = 136,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3198)
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 14,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3211)
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 4,
                            Quantity = 96,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3226)
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 16,
                            Quantity = 65,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3240)
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 53,
                            Quantity = 17,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3255)
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 96,
                            Quantity = 8,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3268)
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 54,
                            Quantity = 93,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3284)
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 20,
                            Quantity = 111,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3298)
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 63,
                            Quantity = 80,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3313)
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 48,
                            Quantity = 163,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3327)
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 69,
                            Quantity = 76,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3342)
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 6,
                            Quantity = 46,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3355)
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 18,
                            Quantity = 60,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3370)
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 18,
                            Quantity = 168,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3383)
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 57,
                            Quantity = 104,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3399)
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 36,
                            Quantity = 65,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3459)
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 83,
                            Quantity = 117,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3475)
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 12,
                            Quantity = 153,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3488)
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 92,
                            Quantity = 118,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3503)
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 53,
                            Quantity = 78,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3517)
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 77,
                            Quantity = 191,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3533)
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 28,
                            Quantity = 49,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3546)
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 90,
                            Quantity = 94,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3562)
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 26,
                            Quantity = 146,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3575)
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 98,
                            Quantity = 182,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3591)
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 87,
                            Quantity = 189,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3605)
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 66,
                            Quantity = 128,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3623)
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 88,
                            Quantity = 132,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3636)
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 45,
                            Quantity = 45,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3652)
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 68,
                            Quantity = 39,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3665)
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 4,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3680)
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 19,
                            Quantity = 13,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3693)
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 89,
                            Quantity = 146,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3719)
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 75,
                            Quantity = 17,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3733)
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 24,
                            Quantity = 3,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3748)
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 1,
                            Quantity = 161,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3761)
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 31,
                            Quantity = 87,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3777)
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 87,
                            Quantity = 108,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3790)
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 45,
                            Quantity = 156,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3806)
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 18,
                            Quantity = 26,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3819)
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 93,
                            Quantity = 136,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3834)
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 45,
                            Quantity = 150,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3847)
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 97,
                            Quantity = 151,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3863)
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 65,
                            Quantity = 42,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3876)
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 15,
                            Quantity = 184,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3891)
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 92,
                            Quantity = 125,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3904)
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 74,
                            Quantity = 99,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3920)
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 9,
                            Quantity = 145,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3933)
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 90,
                            Quantity = 30,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3949)
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 57,
                            Quantity = 102,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3962)
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 33,
                            Quantity = 197,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3979)
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 74,
                            Quantity = 147,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(3992)
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 25,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4017)
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 34,
                            Quantity = 12,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4029)
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 51,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4044)
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 64,
                            Quantity = 182,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4058)
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 63,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4074)
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 93,
                            Quantity = 163,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4087)
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 66,
                            Quantity = 115,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4102)
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 78,
                            Quantity = 154,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4116)
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 82,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4131)
                        },
                        new
                        {
                            Id = 101,
                            ProductId = 3,
                            Quantity = 176,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4145)
                        },
                        new
                        {
                            Id = 102,
                            ProductId = 22,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4161)
                        },
                        new
                        {
                            Id = 103,
                            ProductId = 30,
                            Quantity = 34,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4174)
                        },
                        new
                        {
                            Id = 104,
                            ProductId = 56,
                            Quantity = 188,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4189)
                        },
                        new
                        {
                            Id = 105,
                            ProductId = 59,
                            Quantity = 157,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4202)
                        },
                        new
                        {
                            Id = 106,
                            ProductId = 27,
                            Quantity = 188,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4218)
                        },
                        new
                        {
                            Id = 107,
                            ProductId = 42,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4232)
                        },
                        new
                        {
                            Id = 108,
                            ProductId = 88,
                            Quantity = 30,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4248)
                        },
                        new
                        {
                            Id = 109,
                            ProductId = 41,
                            Quantity = 47,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4262)
                        },
                        new
                        {
                            Id = 110,
                            ProductId = 93,
                            Quantity = 62,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4277)
                        },
                        new
                        {
                            Id = 111,
                            ProductId = 83,
                            Quantity = 135,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4302)
                        },
                        new
                        {
                            Id = 112,
                            ProductId = 77,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4318)
                        },
                        new
                        {
                            Id = 113,
                            ProductId = 55,
                            Quantity = 1,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4331)
                        },
                        new
                        {
                            Id = 114,
                            ProductId = 81,
                            Quantity = 3,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4347)
                        },
                        new
                        {
                            Id = 115,
                            ProductId = 98,
                            Quantity = 100,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4360)
                        },
                        new
                        {
                            Id = 116,
                            ProductId = 37,
                            Quantity = 92,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4375)
                        },
                        new
                        {
                            Id = 117,
                            ProductId = 56,
                            Quantity = 53,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4388)
                        },
                        new
                        {
                            Id = 118,
                            ProductId = 38,
                            Quantity = 180,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4404)
                        },
                        new
                        {
                            Id = 119,
                            ProductId = 8,
                            Quantity = 5,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4418)
                        },
                        new
                        {
                            Id = 120,
                            ProductId = 34,
                            Quantity = 124,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4433)
                        },
                        new
                        {
                            Id = 121,
                            ProductId = 42,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4447)
                        },
                        new
                        {
                            Id = 122,
                            ProductId = 20,
                            Quantity = 194,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4462)
                        },
                        new
                        {
                            Id = 123,
                            ProductId = 29,
                            Quantity = 102,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4476)
                        },
                        new
                        {
                            Id = 124,
                            ProductId = 44,
                            Quantity = 140,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4491)
                        },
                        new
                        {
                            Id = 125,
                            ProductId = 65,
                            Quantity = 26,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4504)
                        },
                        new
                        {
                            Id = 126,
                            ProductId = 51,
                            Quantity = 77,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4520)
                        },
                        new
                        {
                            Id = 127,
                            ProductId = 17,
                            Quantity = 108,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4534)
                        },
                        new
                        {
                            Id = 128,
                            ProductId = 46,
                            Quantity = 38,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4549)
                        },
                        new
                        {
                            Id = 129,
                            ProductId = 78,
                            Quantity = 163,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4563)
                        },
                        new
                        {
                            Id = 130,
                            ProductId = 51,
                            Quantity = 136,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4588)
                        },
                        new
                        {
                            Id = 131,
                            ProductId = 70,
                            Quantity = 179,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4602)
                        },
                        new
                        {
                            Id = 132,
                            ProductId = 75,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4618)
                        },
                        new
                        {
                            Id = 133,
                            ProductId = 81,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4632)
                        },
                        new
                        {
                            Id = 134,
                            ProductId = 91,
                            Quantity = 26,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4648)
                        },
                        new
                        {
                            Id = 135,
                            ProductId = 87,
                            Quantity = 53,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4661)
                        },
                        new
                        {
                            Id = 136,
                            ProductId = 59,
                            Quantity = 44,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4676)
                        },
                        new
                        {
                            Id = 137,
                            ProductId = 73,
                            Quantity = 36,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4690)
                        },
                        new
                        {
                            Id = 138,
                            ProductId = 33,
                            Quantity = 20,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4705)
                        },
                        new
                        {
                            Id = 139,
                            ProductId = 27,
                            Quantity = 145,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4719)
                        },
                        new
                        {
                            Id = 140,
                            ProductId = 80,
                            Quantity = 90,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4734)
                        },
                        new
                        {
                            Id = 141,
                            ProductId = 72,
                            Quantity = 99,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4748)
                        },
                        new
                        {
                            Id = 142,
                            ProductId = 62,
                            Quantity = 121,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4763)
                        },
                        new
                        {
                            Id = 143,
                            ProductId = 5,
                            Quantity = 66,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4776)
                        },
                        new
                        {
                            Id = 144,
                            ProductId = 39,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4792)
                        },
                        new
                        {
                            Id = 145,
                            ProductId = 29,
                            Quantity = 146,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4805)
                        },
                        new
                        {
                            Id = 146,
                            ProductId = 70,
                            Quantity = 4,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4847)
                        },
                        new
                        {
                            Id = 147,
                            ProductId = 23,
                            Quantity = 125,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4861)
                        },
                        new
                        {
                            Id = 148,
                            ProductId = 28,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4876)
                        },
                        new
                        {
                            Id = 149,
                            ProductId = 8,
                            Quantity = 188,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4890)
                        },
                        new
                        {
                            Id = 150,
                            ProductId = 22,
                            Quantity = 85,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4904)
                        },
                        new
                        {
                            Id = 151,
                            ProductId = 4,
                            Quantity = 59,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4918)
                        },
                        new
                        {
                            Id = 152,
                            ProductId = 48,
                            Quantity = 1,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4933)
                        },
                        new
                        {
                            Id = 153,
                            ProductId = 4,
                            Quantity = 170,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4947)
                        },
                        new
                        {
                            Id = 154,
                            ProductId = 8,
                            Quantity = 78,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4962)
                        },
                        new
                        {
                            Id = 155,
                            ProductId = 62,
                            Quantity = 105,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4975)
                        },
                        new
                        {
                            Id = 156,
                            ProductId = 76,
                            Quantity = 195,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(4991)
                        },
                        new
                        {
                            Id = 157,
                            ProductId = 54,
                            Quantity = 154,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5049)
                        },
                        new
                        {
                            Id = 158,
                            ProductId = 44,
                            Quantity = 147,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5065)
                        },
                        new
                        {
                            Id = 159,
                            ProductId = 30,
                            Quantity = 34,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5080)
                        },
                        new
                        {
                            Id = 160,
                            ProductId = 93,
                            Quantity = 103,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5095)
                        },
                        new
                        {
                            Id = 161,
                            ProductId = 96,
                            Quantity = 49,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5109)
                        },
                        new
                        {
                            Id = 162,
                            ProductId = 98,
                            Quantity = 94,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5125)
                        },
                        new
                        {
                            Id = 163,
                            ProductId = 75,
                            Quantity = 187,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5138)
                        },
                        new
                        {
                            Id = 164,
                            ProductId = 52,
                            Quantity = 52,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5154)
                        },
                        new
                        {
                            Id = 165,
                            ProductId = 4,
                            Quantity = 62,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5168)
                        },
                        new
                        {
                            Id = 166,
                            ProductId = 46,
                            Quantity = 62,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5184)
                        },
                        new
                        {
                            Id = 167,
                            ProductId = 60,
                            Quantity = 126,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5198)
                        },
                        new
                        {
                            Id = 168,
                            ProductId = 30,
                            Quantity = 91,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5213)
                        },
                        new
                        {
                            Id = 169,
                            ProductId = 51,
                            Quantity = 180,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5228)
                        },
                        new
                        {
                            Id = 170,
                            ProductId = 71,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5243)
                        },
                        new
                        {
                            Id = 171,
                            ProductId = 54,
                            Quantity = 88,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5257)
                        },
                        new
                        {
                            Id = 172,
                            ProductId = 6,
                            Quantity = 40,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5273)
                        },
                        new
                        {
                            Id = 173,
                            ProductId = 82,
                            Quantity = 81,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5287)
                        },
                        new
                        {
                            Id = 174,
                            ProductId = 72,
                            Quantity = 111,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5303)
                        },
                        new
                        {
                            Id = 175,
                            ProductId = 75,
                            Quantity = 134,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5317)
                        },
                        new
                        {
                            Id = 176,
                            ProductId = 40,
                            Quantity = 110,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5332)
                        },
                        new
                        {
                            Id = 177,
                            ProductId = 93,
                            Quantity = 17,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5397)
                        },
                        new
                        {
                            Id = 178,
                            ProductId = 47,
                            Quantity = 92,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5413)
                        },
                        new
                        {
                            Id = 179,
                            ProductId = 8,
                            Quantity = 175,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5427)
                        },
                        new
                        {
                            Id = 180,
                            ProductId = 38,
                            Quantity = 60,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5443)
                        },
                        new
                        {
                            Id = 181,
                            ProductId = 60,
                            Quantity = 155,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5457)
                        },
                        new
                        {
                            Id = 182,
                            ProductId = 62,
                            Quantity = 122,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5473)
                        },
                        new
                        {
                            Id = 183,
                            ProductId = 1,
                            Quantity = 15,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5487)
                        },
                        new
                        {
                            Id = 184,
                            ProductId = 69,
                            Quantity = 178,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5502)
                        },
                        new
                        {
                            Id = 185,
                            ProductId = 36,
                            Quantity = 44,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5516)
                        },
                        new
                        {
                            Id = 186,
                            ProductId = 6,
                            Quantity = 20,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5531)
                        },
                        new
                        {
                            Id = 187,
                            ProductId = 86,
                            Quantity = 193,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5545)
                        },
                        new
                        {
                            Id = 188,
                            ProductId = 44,
                            Quantity = 107,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5560)
                        },
                        new
                        {
                            Id = 189,
                            ProductId = 65,
                            Quantity = 38,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5574)
                        },
                        new
                        {
                            Id = 190,
                            ProductId = 82,
                            Quantity = 97,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5590)
                        },
                        new
                        {
                            Id = 191,
                            ProductId = 61,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5603)
                        },
                        new
                        {
                            Id = 192,
                            ProductId = 98,
                            Quantity = 97,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5618)
                        },
                        new
                        {
                            Id = 193,
                            ProductId = 41,
                            Quantity = 185,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5632)
                        },
                        new
                        {
                            Id = 194,
                            ProductId = 99,
                            Quantity = 68,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5647)
                        },
                        new
                        {
                            Id = 195,
                            ProductId = 61,
                            Quantity = 104,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5661)
                        },
                        new
                        {
                            Id = 196,
                            ProductId = 98,
                            Quantity = 16,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5676)
                        },
                        new
                        {
                            Id = 197,
                            ProductId = 77,
                            Quantity = 55,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5723)
                        },
                        new
                        {
                            Id = 198,
                            ProductId = 42,
                            Quantity = 30,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5738)
                        },
                        new
                        {
                            Id = 199,
                            ProductId = 44,
                            Quantity = 36,
                            UpdateUtcDateTime = new DateTime(2025, 2, 3, 18, 20, 21, 363, DateTimeKind.Utc).AddTicks(5752)
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", "Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Product 99"
                        });
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Order", b =>
                {
                    b.HasOne("cbData.BE.DB.Models.Products.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cbData.BE.DB.Models.Products.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
